[default]
dependencies = ["build", "ls"]

[ls]
command = ["ls"]

[test]
command = ["go", "test", "-v", "./..."]

[clean]
command = ["go", "clean"]

[build]
command = ["go", "build", "-o", "bake-dev"]
dependencies = ["clean"]

[lint]
dependencies = ["golint", "staticcheck"]

[golint]
command = ["golint", "-set_exit_status"]

[staticcheck]
command = ["staticcheck"]
args = ["./..."]

[install_tools]
command = ["go", "-u", "golang.org/x/lint/golint", "honnef.co/go/tools/cmd/staticcheck"]

[install]
command = ["go", "install"]
dependencies = ["build"]

[lsdir]
commands = [
  ["ls", "-alt"],
  ["dir"],
]
