name: CI
on: [push]
jobs:

  build:
    name: Test
    strategy:
      matrix:
        go: [1.14]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
      env:
        GO111MODULE: on

    - name: Run test
      run: |
        go test -v ./...
